In [1]:
{
  'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 
  'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 
  'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
  'max': [[6, 7, 8], [2, 5, 8], 8],
  'min': [[0, 1, 2], [0, 3, 6], 0],
  'sum': [[9, 12, 15], [3, 12, 21], 36]
}

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

In [2]:
import numpy as np


def calculate(list):
    a = np.array(list)
    calculations = np.sum(a)

    return calculations


list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(calculate(list))


45


In [3]:
import numpy as np


def calculate(list):
    a = np.array(list).reshape(3,3)
    calculations = {'mean': [np.mean(a,axis = 0), np.mean(a,axis = 1), np.mean(a)],
                    'variance': [np.var(a,axis = 0), np.var(a,axis = 1), np.var(a)],
                    'standard deviation': [np.std(a,axis = 0), np.std(a,axis = 1), np.std(a)],
                    'max': [np.max(a,axis = 0), np.max(a,axis = 1), np.max(a)],
                    'min': [np.min(a,axis = 0), np.min(a,axis = 1), np.min(a)],
                    'sum': [np.sum(a,axis = 0), np.sum(a,axis = 1), np.sum(a)]
                   }

    return calculations


list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(calculate(list))

{'mean': [array([4., 5., 6.]), array([2., 5., 8.]), 5.0], 'variance': [array([6., 6., 6.]), array([0.66666667, 0.66666667, 0.66666667]), 6.666666666666667], 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]), array([0.81649658, 0.81649658, 0.81649658]), 2.581988897471611], 'max': [array([7, 8, 9]), array([3, 6, 9]), 9], 'min': [array([1, 2, 3]), array([1, 4, 7]), 1], 'sum': [array([12, 15, 18]), array([ 6, 15, 24]), 45]}


In [4]:
import numpy as np


def calculate(list):
    a = np.array(list).reshape(3,3)
    calculations = {'mean': [np.mean(a,axis = 0), np.mean(a,axis = 1), np.mean(a)],
                    'variance': [np.var(a,axis = 0), np.var(a,axis = 1), np.var(a)],
                    'standard deviation': [np.std(a,axis = 0), np.std(a,axis = 1), np.std(a)],
                    'max': [np.max(a,axis = 0), np.max(a,axis = 1), np.max(a)],
                    'min': [np.min(a,axis = 0), np.min(a,axis = 1), np.min(a)],
                    'sum': [np.sum(a,axis = 0), np.sum(a,axis = 1), np.sum(a)]
        
                   }

    return calculations


list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
for key,value in calculate(list).items():
    print(key,':',value)

mean : [array([4., 5., 6.]), array([2., 5., 8.]), 5.0]
variance : [array([6., 6., 6.]), array([0.66666667, 0.66666667, 0.66666667]), 6.666666666666667]
standard deviation : [array([2.44948974, 2.44948974, 2.44948974]), array([0.81649658, 0.81649658, 0.81649658]), 2.581988897471611]
max : [array([7, 8, 9]), array([3, 6, 9]), 9]
min : [array([1, 2, 3]), array([1, 4, 7]), 1]
sum : [array([12, 15, 18]), array([ 6, 15, 24]), 45]


In [5]:
import numpy as np
import pprint


def calculate(list):
    a = np.array(list).reshape(3,3)
    calculations = {'mean': [np.mean(a,axis = 0), np.mean(a,axis = 1), np.mean(a)],
                    'variance': [np.var(a,axis = 0), np.var(a,axis = 1), np.var(a)],
                    'standard deviation': [np.std(a,axis = 0), np.std(a,axis = 1), np.std(a)],
                    'max': [np.max(a,axis = 0), np.max(a,axis = 1), np.max(a)],
                    'min': [np.min(a,axis = 0), np.min(a,axis = 1), np.min(a)],
                    'sum': [np.sum(a,axis = 0), np.sum(a,axis = 1), np.sum(a)]
                   }

    return calculations


list = [0,1,2,3,4,5,6,7,8] 
if len(list) == 9:
    pprint.pprint(calculate(list),sort_dicts = False)
else:
    print('List must contain nine numbers.')

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0],
 'variance': [array([6., 6., 6.]),
              array([0.66666667, 0.66666667, 0.66666667]),
              6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
                        array([0.81649658, 0.81649658, 0.81649658]),
                        2.581988897471611],
 'max': [array([6, 7, 8]), array([2, 5, 8]), 8],
 'min': [array([0, 1, 2]), array([0, 3, 6]), 0],
 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}


In [6]:
import numpy as np
import pprint


def calculate(list):
    if len(list) != 9:
        raise ValueError ('List must contain nine numbers.')
    a = np.array(list).reshape(3,3)

    return {'mean': [np.mean(a,axis = 0), np.mean(a,axis = 1), np.mean(a)],
                    'variance': [np.var(a,axis = 0), np.var(a,axis = 1), np.var(a)],
                    'standard deviation': [np.std(a,axis = 0), np.std(a,axis = 1), np.std(a)],
                    'max': [np.max(a,axis = 0), np.max(a,axis = 1), np.max(a)],
                    'min': [np.min(a,axis = 0), np.min(a,axis = 1), np.min(a)],
                    'sum': [np.sum(a,axis = 0), np.sum(a,axis = 1), np.sum(a)]
                   }


list = [0,1,2,3,4,5,6,7,8] 
pprint.pprint(calculate(list),sort_dicts = False)

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0],
 'variance': [array([6., 6., 6.]),
              array([0.66666667, 0.66666667, 0.66666667]),
              6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
                        array([0.81649658, 0.81649658, 0.81649658]),
                        2.581988897471611],
 'max': [array([6, 7, 8]), array([2, 5, 8]), 8],
 'min': [array([0, 1, 2]), array([0, 3, 6]), 0],
 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}


In [7]:
import numpy as np
import pprint


def calculate(list):
    if len(list) != 9:
        raise ValueError ('List must contain nine numbers.')
    a = np.array(list).reshape(3,3)
    meanrows = []
    ls = [a.mean(axis=0)]
    for i in range(3):
        meanrows.append(ls[0][i])
        
    meancols = []
    ls = [a.mean(axis=1)]
    for i in range(3):
        meancols.append(ls[0][i])
        
    varrows = []
    ls = [a.var(axis=0)]
    for i in range(3):
        varrows.append(ls[0][i])
        
    varcols = []
    ls = [a.var(axis=1)]
    for i in range(3):
        varcols.append(ls[0][i])
        
    stdrows = []
    ls = [a.std(axis=0)]
    for i in range(3):
        stdrows.append(ls[0][i])
        
    stdcols = []
    ls = [a.std(axis=1)]
    for i in range(3):
        stdcols.append(ls[0][i])
        
    maxrows = []
    ls = [a.max(axis=0)]
    for i in range(3):
        maxrows.append(ls[0][i])
        
    maxcols = []
    ls = [a.max(axis=1)]
    for i in range(3):
        maxcols.append(ls[0][i])
        
    minrows = []
    ls = [a.min(axis=0)]
    for i in range(3):
        minrows.append(ls[0][i])
        
    mincols = []
    ls = [a.min(axis=1)]
    for i in range(3):
        mincols.append(ls[0][i])
        
    sumrows = []
    ls = [a.sum(axis=0)]
    for i in range(3):
        sumrows.append(ls[0][i])
        
    sumcols = []
    ls = [a.sum(axis=1)]
    for i in range(3):
        sumcols.append(ls[0][i])

    return {'mean': [meanrows, meancols, np.mean(a)],
                    'variance': [varrows, varcols, np.var(a)],
                    'standard deviation': [stdrows, stdcols, np.std(a)],
                    'max': [maxrows, maxcols, np.max(a)],
                    'min': [minrows, mincols, np.min(a)],
                    'sum': [sumrows, sumcols, np.sum(a)]
                   }


list = [0,1,2,3,4,5,6,7,8] 
pprint.pprint(calculate(list),sort_dicts = False)

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
              [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
              6.666666666666667],
 'standard deviation': [[2.449489742783178,
                         2.449489742783178,
                         2.449489742783178],
                        [0.816496580927726,
                         0.816496580927726,
                         0.816496580927726],
                        2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}
